services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=t1_homework'
      - 'POSTGRES_PASSWORD=0000'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'

  zookeeper_t1:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper_t1
    container_name: zookeeper
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
  broker_t1:
    image: confluentinc/cp-kafka:5.5.0
    hostname: broker_t1
    container_name: broker
    depends_on:
      - zookeeper_t1
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper_t1:2182'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker_t1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

#  client-service:
#    depends_on: [postgres]
#    build: ./client
#    environment:
#      DB_HOST: postgres
#    ports:
#      - "8081:8080"
#
#  transaction-service:
#    depends_on: [postgres]
#    build: ./transaction
#    environment:
#      KAFKA_SERVER: broker_t1
#    ports:
#      - "8082:8080"
#
#  correction-service:
#    depends_on: [postgres]
#    build: ./correction
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/t1_homework
#    ports:
#      - "8083:8080"