server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/t1_homework
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.default_schema: client_schema
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: client_schema
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/t1_homework
    user: postgres
    password: "0000"
    enabled: true


t1:
  credit-limit: 10000.00
  kafka:
    topic:
      transaction-process: t1_demo_client_transactions
      error-transaction: t1_demo_client_transaction_errors
      correction-transaction: t1_demo_transaction_correction
    listener:
      transaction-process: transaction-process
      transaction-correction: transaction-correction
    bootstrap-servers: ${KAFKA_SERVER:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: my-group

