server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/t1_homework
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver


t1:
  credit-limit: 10000.00
  kafka:
    topic:
      transaction-process: t1_demo_client_transactions
      error-transaction: t1_demo_client_transaction_errors
      correction-transaction: t1_demo_transaction_correction
    listener:
      transaction-process: transaction-process
      transaction-correction: transaction-correction
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group

#security:
#  jwt:
#    secret: mysecretkey  # ????????? ???? ??? ?????????? JWT
#    expiration: 3600000  # ????? ????? ?????? ? ?????????????

